#!/bin/bash

###############################################
#
# check latest raspbian kernel version, download it to directory tmp
#
#################################################

# get latest raspbian kernel version
wget -q http://archive.raspberrypi.org/debian/dists/stretch/main/binary-armhf/Packages.gz -O - | gunzip \
| awk '/^Package: raspberrypi-kernel-headers[[:blank:]]*$/ { ok=1; next} /^Package: / {ok=0;} (ok!=1) {next} 
	/^Version: / {print "RPI_FIRMWARE_VER=" $2 } 
	/^Filename: / {print "RPI_FIRMWARE_FILE=" $2; nextfile }' > .raspbian-versions

# compare with locally installed version
if [ ! -d tmp ]; then
	[ -f tmp ] && rm -f tmp 
else 
	if diff -s .raspbian-versions tmp/versions >/dev/null 2>&1; then
		# kernel headers are loaded
		exit 0
	fi
	rm -rf tmp
fi
mkdir tmp

. .raspbian-versions

# Dowload current raspbian kernel source
# get commit number used for making this kernel version
cd tmp
wget https://raw.githubusercontent.com/raspberrypi/firmware/stable/extra/git_hash -O- > .git_hash
GIT_VER=`cat .git_hash`
	wget https://github.com/raspberrypi/linux/archive/$GIT_VER.zip -O raspberrypi-kernel_${RPI_FIRMWARE_VER}.zip
	unzip raspberrypi-kernel_${RPI_FIRMWARE_VER}.zip
	mv linux-$GIT_VER linux-raspberrypi-kernel_${RPI_FIRMWARE_VER}
	#-----------------------------------------------------------------------
	rm raspberrypi-kernel_${RPI_FIRMWARE_VER}.zip

# download headers and symbols
wget http://archive.raspberrypi.org/debian/${RPI_FIRMWARE_FILE}
dpkg-deb -x `basename ${RPI_FIRMWARE_FILE}` h
cd ..
cat .raspbian-versions >tmp/versions
