#!/bin/bash

mkdir -p tmp
wget -q http://archive.raspberrypi.org/debian/dists/stretch/main/binary-armhf/Packages.gz -O - | gunzip \
| awk '/^Package: raspberrypi-kernel-headers[[:blank:]]*$/ { ok=1; next} /^Package: / {ok=0;} (ok!=1) {next} 
/^Version: / {print "RPI_FIRMWARE_VER=" $2 } 
/^Filename: / {print "RPI_FIRMWARE_FILE=" $2; nextfile }' > tmp/versions

cd tmp
. versions

wget https://github.com/raspberrypi/linux/archive/raspberrypi-kernel_${RPI_FIRMWARE_VER}.zip

unzip raspberrypi-kernel_${RPI_FIRMWARE_VER}.zip
rm raspberrypi-kernel_${RPI_FIRMWARE_VER}.zip

wget http://archive.raspberrypi.org/debian/${RPI_FIRMWARE_FILE}
dpkg-deb -x raspberrypi-kernel-headers_1.20180417-1_armhf.deb h
KERNEL_VER=`ls -1 h/lib/modules | grep '\-v7'`
echo $KERNEL_VER
cp h/usr/src/linux-headers-${KERNEL_VER}/.config linux-raspberrypi-kernel_${RPI_FIRMWARE_VER}
cp h/usr/src/linux-headers-${KERNEL_VER}/Module.symvers linux-raspberrypi-kernel_${RPI_FIRMWARE_VER}
cd linux-raspberrypi-kernel_${RPI_FIRMWARE_VER}
make modules_prepare CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm
cd ../..
make all CCPREFIX=arm-linux-gnueabi- ARCH=arm LINUX_DIR_PATH=tmp/linux-raspberrypi-kernel_${RPI_FIRMWARE_VER}
