
obj-$(CONFIG_UNIPI_SPI) += unipi.o
obj-$(CONFIG_UNIPI_MODBUS) += unipi_modbus.o
obj-$(CONFIG_UNIPI_IOGROUP) += unipi_iogroup_bus.o
obj-$(CONFIG_UNIPI_MFD) += unipi_mfd.o
obj-$(CONFIG_UNIPI_LED) += unipi_leds.o
obj-$(CONFIG_UNIPI_GPIO) += unipi_gpio.o
obj-$(CONFIG_UNIPI_IIO) += unipi_iio.o
obj-$(CONFIG_UNIPI_IIO) += unipi_iio_legacy.o
obj-$(CONFIG_UNIPI_UART) += unipi-uart.o
obj-$(CONFIG_UNIPI_DALI) += unipi_dali.o

unipi-objs := unipi_spi.o unipi_spi_op.o unipi_spi_op2.o unipi_spi_firmware.o unipi_regmap.o unipi_channel.o
unipi-uart-objs := unipi_uart.o unipi_tty.o
